### ISSUE TITLE
Inquiring about register the Chamber.jl

### ISSUE THREAD

**Issue by CallieHsu** [brown-ccv/Chamber.jl#220]
Hi @cpaniaguam

I have pushed the latest code changes to the master branch and updated the [README.md](https://github.com/brown-ccv/Chamber.jl#readme). @chris-huber and I believe that our code is now ready for others to try out and provide feedback. We are thinking of registering the package and would appreciate your guidance on any additional steps we need to take before proceeding with the registration process.

I came across this process on how to register a package: https://julialang.org/contribute/developing_package/#step_5_register_your_package. Since our code is hosted by CCV, I was wondering if there are any differences in the registration process that we need to be aware of.

Thank you for your assistance.

**Comment by cpaniaguam** [comment]
The package looks very good, and I am exited that the team has decided to register it in the Julia registry so everyone can use it!

Because the package is now hosted within the brown-ccv organization, a member of the organization must initiate the registration process. I can take care of this for you. Before doing this, however, the documentation PR should also be merged so that users can access the package's API docs (and more) in a GitHub pages site. I can also do this for you!

I have made the repo public so anyone with the link to the repo https://github.com/brown-ccv/Chamber.jl can start using the package even if it is not registered yet. I plan to take care of all this early next week.

I'd like to congratulate you @CallieHsu for such great work! I had a great time collaborating with you on this project!!

Cheers,
Carlos

**Comment by CallieHsu** [comment]
@cpaniaguam Thanks for your kind words! I'm excited the package is available to everyone with the repo link. I appreciate your help in initiating the registration process and also the documentation PR. It was great collaborating with you. Have a nice weekends!

**Comment by cpaniaguam** [comment]
@JuliaRegistrator register

**Comment by CallieHsu** [comment]
@cpaniaguam Thanks for your help with the registration process. I was just wondering, based on your experience, how long it typically takes for the package to be merged and become available for others to use?

**Comment by cpaniaguam** [comment]
> @cpaniaguam Thanks for your help with the registration process. I was just wondering, based on your experience, how long it typically takes for the package to be merged and become available for others to use?

About 3 days. See https://github.com/JuliaRegistries/General#:~:text=Currently%20the%20waiting,for%20community%20feedback)

**Comment by cpaniaguam** [comment]
@JuliaRegistrator register

**Comment by cpaniaguam** [comment]
All checks have passed! https://github.com/JuliaRegistries/General/pull/82806

Now we wait until Chamber.jl is added to the registry (likely by Monday or Tuesday). Afterwards we do as in https://github.com/brown-ccv/Chamber.jl/issues/220#issuecomment-1536688874 to finish the process.
